name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-composer:
    name: "Validate dependency installation"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extensions: [ "scoutapm", "" ]
        twig-version:
          - "2.*"
          - "3.*"
        symfony-version:
          - "4.*"
          - "5.*"
          - "6.*"
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        exclude:
          - { symfony-version: "4.*", "twig-version": "3.*", php-version: "7.1" } # Twig 3 (on Symfony 4) requires 7.2+
          - { symfony-version: "5.*", php-version: "7.1" } # Symfony 5 requires 7.2+
          - { symfony-version: "6.*", php-version: "7.1" } # Symfony 6 requires 8.0+
          - { symfony-version: "6.*", php-version: "7.2" } # Symfony 6 requires 8.0+
          - { symfony-version: "6.*", php-version: "7.3" } # Symfony 6 requires 8.0+
          - { symfony-version: "6.*", php-version: "7.4" } # Symfony 6 requires 8.0+
    steps:
      - uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: ${{ matrix.extensions }}
      # --no-update then a full `composer update` is needed to overcome locked dependencies
      # See: https://github.com/composer/composer/issues/9561
      - name: "Require Symfony ${{ matrix.symfony-version }}, Twig ${{ matrix.twig-version }}"
        run: "composer require symfony/symfony:${{ matrix.symfony-version }} twig/twig:${{ matrix.twig-version }} --no-update --no-interaction --prefer-dist --prefer-stable"
      - name: "Composer update with new requirements"
        run: "composer update --no-interaction --prefer-dist --prefer-stable"
